name: YouTube Download

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yt-dlp
        run: |
          sudo pip install yt-dlp

      - name: Create cookies.txt from secret
        run: |
          echo "${{ secrets.COOKIES }}" > cookies.txt

      - name: Download YouTube Video
        run: |
          yt-dlp --cookies cookies.txt "https://www.youtube.com/watch?v=zzwRbKI2pn4"
